import {
  AnimalConfig,
  AnimalId,
  CropConfig,
  CropId,
  DailyQuest,
  Achievement,
  FactoryConfig,
  FactoryId,
  GameState,
  RecipeConfig,
  WeatherInfo,
  WeatherType,
  CustomerOrder,
} from '../types/game';

export const CROPS: Record<CropId, CropConfig> = {
  wheat: {
    id: 'wheat',
    name: 'Wheat',
    nameVi: 'Lúa mì',
    growTime: 6, // 6 seconds for brisk satisfying mobile gameplay
    buyCost: 2,
    sellPrice: 5,
    expReward: 4,
    minLevel: 1,
    icon: '🌾',
    color: '#EAB308',
    bgLight: '#FEF9C3',
  },
  carrot: {
    id: 'carrot',
    name: 'Carrot',
    nameVi: 'Cà rốt',
    growTime: 12,
    buyCost: 5,
    sellPrice: 12,
    expReward: 8,
    minLevel: 1,
    icon: '🥕',
    color: '#F97316',
    bgLight: '#FFEDD5',
  },
  corn: {
    id: 'corn',
    name: 'Corn',
    nameVi: 'Bắp ngô',
    growTime: 20,
    buyCost: 10,
    sellPrice: 22,
    expReward: 14,
    minLevel: 2,
    icon: '🌽',
    color: '#FBBF24',
    bgLight: '#FEF3C7',
  },
  tomato: {
    id: 'tomato',
    name: 'Tomato',
    nameVi: 'Cà chua',
    growTime: 32,
    buyCost: 16,
    sellPrice: 38,
    expReward: 22,
    minLevel: 3,
    icon: '🍅',
    color: '#EF4444',
    bgLight: '#FEE2E2',
  },
  strawberry: {
    id: 'strawberry',
    name: 'Strawberry',
    nameVi: 'Dâu tây',
    growTime: 48,
    buyCost: 25,
    sellPrice: 60,
    expReward: 35,
    minLevel: 4,
    icon: '🍓',
    color: '#EC4899',
    bgLight: '#FCE7F3',
  },
  pumpkin: {
    id: 'pumpkin',
    name: 'Pumpkin',
    nameVi: 'Bí ngô',
    growTime: 70,
    buyCost: 40,
    sellPrice: 100,
    expReward: 55,
    minLevel: 5,
    icon: '🎃',
    color: '#EA580C',
    bgLight: '#FFEDD5',
  },
};

export const ANIMALS: Record<AnimalId, AnimalConfig> = {
  chicken: {
    id: 'chicken',
    name: 'Chicken',
    nameVi: 'Gà đẻ trứng',
    produceNameVi: 'Trứng gà',
    feedCropId: 'wheat',
    produceItemId: 'egg',
    produceTime: 15,
    minLevel: 1,
    expReward: 10,
    buyCost: 60,
    icon: '🐔',
    produceIcon: '🥚',
    color: '#F59E0B',
  },
  cow: {
    id: 'cow',
    name: 'Cow',
    nameVi: 'Bò sữa',
    produceNameVi: 'Sữa tươi',
    feedCropId: 'corn',
    produceItemId: 'milk',
    produceTime: 30,
    minLevel: 2,
    expReward: 20,
    buyCost: 150,
    icon: '🐮',
    produceIcon: '🥛',
    color: '#3B82F6',
  },
  sheep: {
    id: 'sheep',
    name: 'Sheep',
    nameVi: 'Cừu lấy lông',
    produceNameVi: 'Lông cừu',
    feedCropId: 'carrot',
    produceItemId: 'wool',
    produceTime: 45,
    minLevel: 3,
    expReward: 32,
    buyCost: 280,
    icon: '🐑',
    produceIcon: '🧶',
    color: '#8B5CF6',
  },
  pig: {
    id: 'pig',
    name: 'Pig',
    nameVi: 'Heo tìm nấm',
    produceNameVi: 'Nấm quý',
    feedCropId: 'pumpkin',
    produceItemId: 'truffle',
    produceTime: 65,
    minLevel: 5,
    expReward: 50,
    buyCost: 450,
    icon: '🐷',
    produceIcon: '🍄',
    color: '#EC4899',
  },
};

export const FACTORIES: Record<FactoryId, FactoryConfig> = {
  windmill: {
    id: 'windmill',
    nameVi: 'Cối Xay Gió',
    icon: '💨',
    color: '#10B981',
    minLevel: 1,
    cost: 100,
    descriptionVi: 'Xay lúa mì thành bột mì mịn màng thơm phức',
  },
  bakery: {
    id: 'bakery',
    nameVi: 'Lò Bánh Mì',
    icon: '🥖',
    color: '#F59E0B',
    minLevel: 2,
    cost: 250,
    descriptionVi: 'Nướng những mẻ bánh mì giòn tan và bánh ngọt hảo hạng',
  },
  dairy: {
    id: 'dairy',
    nameVi: 'Xưởng Chế Biến Sữa',
    icon: '🧀',
    color: '#3B82F6',
    minLevel: 3,
    cost: 400,
    descriptionVi: 'Lên men sữa bò thành phô mai thơm ngậy và bơ vàng',
  },
  juicePress: {
    id: 'juicePress',
    nameVi: 'Máy Ép Nước Trái Cây',
    icon: '🥤',
    color: '#EC4899',
    minLevel: 4,
    cost: 600,
    descriptionVi: 'Chiết xuất nước ép vitamin tươi mát từ nông sản',
  },
};

export const RECIPES: RecipeConfig[] = [
  {
    id: 'flour',
    nameVi: 'Túi Bột Mì',
    factoryId: 'windmill',
    craftTime: 12,
    ingredients: [{ itemId: 'wheat', count: 2 }],
    outputCount: 1,
    expReward: 12,
    sellPrice: 18,
    icon: '🌾',
    minLevel: 1,
  },
  {
    id: 'cornMeal',
    nameVi: 'Bột Bắp Vàng',
    factoryId: 'windmill',
    craftTime: 18,
    ingredients: [{ itemId: 'corn', count: 2 }],
    outputCount: 1,
    expReward: 18,
    sellPrice: 48,
    icon: '🌽',
    minLevel: 2,
  },
  {
    id: 'bread',
    nameVi: 'Bánh Mì Nóng',
    factoryId: 'bakery',
    craftTime: 20,
    ingredients: [
      { itemId: 'flour', count: 1 },
      { itemId: 'egg', count: 1 },
    ],
    outputCount: 1,
    expReward: 25,
    sellPrice: 55,
    icon: '🍞',
    minLevel: 2,
  },
  {
    id: 'cornBread',
    nameVi: 'Bánh Bắp Nướng',
    factoryId: 'bakery',
    craftTime: 30,
    ingredients: [
      { itemId: 'cornMeal', count: 1 },
      { itemId: 'egg', count: 1 },
    ],
    outputCount: 1,
    expReward: 35,
    sellPrice: 85,
    icon: '🥧',
    minLevel: 3,
  },
  {
    id: 'strawberryCake',
    nameVi: 'Bánh Kem Dâu Tây',
    factoryId: 'bakery',
    craftTime: 45,
    ingredients: [
      { itemId: 'flour', count: 1 },
      { itemId: 'strawberry', count: 2 },
      { itemId: 'egg', count: 1 },
    ],
    outputCount: 1,
    expReward: 55,
    sellPrice: 160,
    icon: '🍰',
    minLevel: 4,
  },
  {
    id: 'butter',
    nameVi: 'Bơ Tươi',
    factoryId: 'dairy',
    craftTime: 25,
    ingredients: [{ itemId: 'milk', count: 1 }],
    outputCount: 1,
    expReward: 28,
    sellPrice: 65,
    icon: '🧈',
    minLevel: 3,
  },
  {
    id: 'cheese',
    nameVi: 'Phô Mai Béo',
    factoryId: 'dairy',
    craftTime: 40,
    ingredients: [{ itemId: 'milk', count: 2 }],
    outputCount: 1,
    expReward: 45,
    sellPrice: 130,
    icon: '🧀',
    minLevel: 3,
  },
  {
    id: 'tomatoJuice',
    nameVi: 'Nước Ép Cà Chua',
    factoryId: 'juicePress',
    craftTime: 25,
    ingredients: [{ itemId: 'tomato', count: 2 }],
    outputCount: 1,
    expReward: 30,
    sellPrice: 90,
    icon: '🧃',
    minLevel: 4,
  },
  {
    id: 'strawberryShake',
    nameVi: 'Sinh Tố Dâu Sữa',
    factoryId: 'juicePress',
    craftTime: 40,
    ingredients: [
      { itemId: 'strawberry', count: 2 },
      { itemId: 'milk', count: 1 },
    ],
    outputCount: 1,
    expReward: 50,
    sellPrice: 180,
    icon: '🥤',
    minLevel: 4,
  },
];

export const ITEM_CATALOG: Record<
  string,
  { nameVi: string; icon: string; category: 'crop' | 'animal' | 'product'; sellPrice: number }
> = {
  // Crops
  wheat: { nameVi: 'Lúa mì', icon: '🌾', category: 'crop', sellPrice: 5 },
  carrot: { nameVi: 'Cà rốt', icon: '🥕', category: 'crop', sellPrice: 12 },
  corn: { nameVi: 'Bắp ngô', icon: '🌽', category: 'crop', sellPrice: 22 },
  tomato: { nameVi: 'Cà chua', icon: '🍅', category: 'crop', sellPrice: 38 },
  strawberry: { nameVi: 'Dâu tây', icon: '🍓', category: 'crop', sellPrice: 60 },
  pumpkin: { nameVi: 'Bí ngô', icon: '🎃', category: 'crop', sellPrice: 100 },
  // Animal goods
  egg: { nameVi: 'Trứng gà', icon: '🥚', category: 'animal', sellPrice: 15 },
  milk: { nameVi: 'Sữa tươi', icon: '🥛', category: 'animal', sellPrice: 35 },
  wool: { nameVi: 'Lông cừu', icon: '🧶', category: 'animal', sellPrice: 65 },
  truffle: { nameVi: 'Nấm quý', icon: '🍄', category: 'animal', sellPrice: 120 },
  // Factory items
  flour: { nameVi: 'Túi Bột mì', icon: '🌾', category: 'product', sellPrice: 18 },
  cornMeal: { nameVi: 'Bột Bắp vàng', icon: '🌽', category: 'product', sellPrice: 48 },
  bread: { nameVi: 'Bánh Mì', icon: '🍞', category: 'product', sellPrice: 55 },
  cornBread: { nameVi: 'Bánh Bắp', icon: '🥧', category: 'product', sellPrice: 85 },
  strawberryCake: { nameVi: 'Bánh Kem Dâu', icon: '🍰', category: 'product', sellPrice: 160 },
  butter: { nameVi: 'Bơ Tươi', icon: '🧈', category: 'product', sellPrice: 65 },
  cheese: { nameVi: 'Phô Mai', icon: '🧀', category: 'product', sellPrice: 130 },
  tomatoJuice: { nameVi: 'Nước Cà Chua', icon: '🧃', category: 'product', sellPrice: 90 },
  strawberryShake: { nameVi: 'Sinh Tố Dâu', icon: '🥤', category: 'product', sellPrice: 180 },
};

export const WEATHERS: Record<WeatherType, WeatherInfo> = {
  sunny: {
    type: 'sunny',
    nameVi: 'Trời Nắng Đẹp',
    descriptionVi: 'Ánh nắng ấm áp, cây cối phát triển khỏe mạnh tự nhiên.',
    buffVi: 'Tốc độ tiêu chuẩn 100%',
    icon: '☀️',
  },
  rainy: {
    type: 'rainy',
    nameVi: 'Mưa Rào Mát Lành',
    descriptionVi: 'Cơn mưa tưới tắm cho đất, tự động tưới nước toàn bộ ô đất!',
    buffVi: 'Tự động tưới nước x2 tốc độ cây trồng!',
    icon: '🌧️',
  },
  rainbow: {
    type: 'rainbow',
    nameVi: 'Cầu Vồng May Mắn',
    descriptionVi: 'Sau cơn mưa cầu vồng xuất hiện, lái buôn thị trấn mua giá cao!',
    buffVi: '+50% Tiền thưởng giao hàng xe tải!',
    icon: '🌈',
  },
  breeze: {
    type: 'breeze',
    nameVi: 'Gió Mát Đồng Quê',
    descriptionVi: 'Gió lành làm đàn gà vịt bò cừu vui vẻ nhảy múa cả ngày!',
    buffVi: '-25% thời gian cho thú nuôi sản xuất!',
    icon: '🍃',
  },
};

export const LEVEL_EXP_MAP: number[] = [
  0,
  60,    // Lvl 1 -> 2
  150,   // Lvl 2 -> 3
  300,   // Lvl 3 -> 4
  520,   // Lvl 4 -> 5
  800,   // Lvl 5 -> 6
  1150,  // Lvl 6 -> 7
  1600,  // Lvl 7 -> 8
  2200,  // Lvl 8 -> 9
  3000,  // Lvl 9 -> 10
  4000,  // Lvl 10 -> 11
  5200,  // Lvl 11 -> 12
  6600,  // Lvl 12 -> 13
  8200,  // Lvl 13 -> 14
  10000, // Lvl 14 -> 15
  13000, // Lvl 15 -> 16
  17000, // Lvl 16 -> 17
  22000, // Lvl 17 -> 18
  28000, // Lvl 18 -> 19
  35000, // Lvl 19 -> 20
];

export function getMaxExpForLevel(level: number): number {
  if (level < LEVEL_EXP_MAP.length) {
    return LEVEL_EXP_MAP[level];
  }
  return 35000 + (level - 20) * 10000;
}

export const INITIAL_ORDERS: CustomerOrder[] = [
  {
    id: 'ord_1',
    customerName: 'Bác Ba Làm Vườn',
    customerRoleVi: 'Hàng Xóm Tốt Bụng',
    avatarSeed: 'uncle_ba',
    avatarEmoji: '👨‍🌾',
    requirements: [
      { itemId: 'wheat', nameVi: 'Lúa mì', icon: '🌾', count: 4 },
      { itemId: 'carrot', nameVi: 'Cà rốt', icon: '🥕', count: 2 },
    ],
    rewardCoins: 45,
    rewardExp: 25,
    rewardGems: 1,
  },
  {
    id: 'ord_2',
    customerName: 'Đầu Bếp Gordon',
    customerRoleVi: 'Bếp Trưởng Thị Trấn',
    avatarSeed: 'chef_gordon',
    avatarEmoji: '👨‍🍳',
    requirements: [
      { itemId: 'egg', nameVi: 'Trứng gà', icon: '🥚', count: 3 },
      { itemId: 'carrot', nameVi: 'Cà rốt', icon: '🥕', count: 3 },
    ],
    rewardCoins: 95,
    rewardExp: 45,
  },
  {
    id: 'ord_3',
    customerName: 'Cô Lan Tiệm Tạp Hóa',
    customerRoleVi: 'Chủ Tiệm Bách Hóa',
    avatarSeed: 'miss_lan',
    avatarEmoji: '👩‍💼',
    requirements: [
      { itemId: 'flour', nameVi: 'Túi Bột Mì', icon: '🌾', count: 2 },
      { itemId: 'egg', nameVi: 'Trứng gà', icon: '🥚', count: 2 },
    ],
    rewardCoins: 110,
    rewardExp: 50,
    rewardGems: 1,
  },
  {
    id: 'ord_4',
    customerName: 'Bé Na Mê Bánh',
    customerRoleVi: 'Khách Hàng Nhí',
    avatarSeed: 'little_na',
    avatarEmoji: '👧',
    requirements: [
      { itemId: 'bread', nameVi: 'Bánh Mì', icon: '🍞', count: 1 },
      { itemId: 'milk', nameVi: 'Sữa tươi', icon: '🥛', count: 2 },
    ],
    rewardCoins: 160,
    rewardExp: 70,
    rewardGems: 2,
  },
];

export const INITIAL_QUESTS: DailyQuest[] = [
  {
    id: 'q_harvest',
    titleVi: 'Nông Dân Chăm Chỉ',
    descriptionVi: 'Thu hoạch 6 cây trồng bất kỳ trên cánh đồng',
    targetCount: 6,
    currentCount: 0,
    rewardCoins: 50,
    rewardExp: 30,
    rewardGems: 1,
    isCompleted: false,
    isClaimed: false,
    icon: '🌾',
  },
  {
    id: 'q_feed',
    titleVi: 'Bạn Của Muôn Loài',
    descriptionVi: 'Cho các con vật trong chuồng ăn 3 lần',
    targetCount: 3,
    currentCount: 0,
    rewardCoins: 60,
    rewardExp: 35,
    rewardGems: 1,
    isCompleted: false,
    isClaimed: false,
    icon: '🐔',
  },
  {
    id: 'q_deliver',
    titleVi: 'Chuyến Xe Tốc Hành',
    descriptionVi: 'Giao thành công 2 chuyến hàng xe tải về thị trấn',
    targetCount: 2,
    currentCount: 0,
    rewardCoins: 100,
    rewardExp: 60,
    rewardGems: 2,
    isCompleted: false,
    isClaimed: false,
    icon: '🚚',
  },
  {
    id: 'q_factory',
    titleVi: 'Nghệ Nhân Chế Biến',
    descriptionVi: 'Sản xuất 2 món thành phẩm trong xưởng chế biến',
    targetCount: 2,
    currentCount: 0,
    rewardCoins: 80,
    rewardExp: 45,
    rewardGems: 1,
    isCompleted: false,
    isClaimed: false,
    icon: '🥖',
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach_1',
    titleVi: 'Bước Đầu Khởi Nghiệp',
    descriptionVi: 'Thu hoạch tổng cộng 25 vụ mùa hoa màu',
    icon: '🌱',
    targetCount: 25,
    currentCount: 0,
    rewardGems: 5,
    isUnlocked: false,
    isClaimed: false,
  },
  {
    id: 'ach_2',
    titleVi: 'Trang Trại Trù Phú',
    descriptionVi: 'Thu thập 15 sản phẩm từ chuồng gia súc',
    icon: '🥛',
    targetCount: 15,
    currentCount: 0,
    rewardGems: 8,
    isUnlocked: false,
    isClaimed: false,
  },
  {
    id: 'ach_3',
    titleVi: 'Thương Gia Đồng Quê',
    descriptionVi: 'Hoàn thành 10 đơn hàng xe tải giao đến thị trấn',
    icon: '🚛',
    targetCount: 10,
    currentCount: 0,
    rewardGems: 12,
    isUnlocked: false,
    isClaimed: false,
  },
  {
    id: 'ach_4',
    titleVi: 'Nông Dân Triệu Phú',
    descriptionVi: 'Kiếm được tích lũy 1,000 đồng vàng từ buôn bán',
    icon: '💰',
    targetCount: 1000,
    currentCount: 0,
    rewardGems: 15,
    isUnlocked: false,
    isClaimed: false,
  },
];

export const DEFAULT_INITIAL_STATE: GameState = {
  farmerName: 'Bác Tư Vui Vẻ',
  level: 1,
  exp: 0,
  coins: 150,
  gems: 10,
  barnCapacity: 60,
  inventory: {
    wheat: 8,
    carrot: 4,
    corn: 2,
    egg: 2,
    flour: 1,
  },
  plots: [
    { id: 1, cropId: 'wheat', plantedAt: Date.now() - 3000, duration: 6, watered: true, fertilized: false },
    { id: 2, cropId: 'wheat', plantedAt: Date.now() - 5000, duration: 6, watered: false, fertilized: false },
    { id: 3, cropId: 'carrot', plantedAt: Date.now() - 4000, duration: 12, watered: true, fertilized: false },
    { id: 4, cropId: null, plantedAt: null, duration: 0, watered: false, fertilized: false },
    { id: 5, cropId: null, plantedAt: null, duration: 0, watered: false, fertilized: false },
    { id: 6, cropId: null, plantedAt: null, duration: 0, watered: false, fertilized: false },
  ],
  animalPens: {
    chicken: {
      id: 'chicken',
      unlocked: true,
      animalCount: 3,
      maxAnimals: 6,
      isFed: true,
      fedAt: Date.now() - 5000,
      duration: 15,
      readyToCollect: 1,
    },
    cow: {
      id: 'cow',
      unlocked: false,
      animalCount: 2,
      maxAnimals: 4,
      isFed: false,
      fedAt: null,
      duration: 30,
      readyToCollect: 0,
    },
    sheep: {
      id: 'sheep',
      unlocked: false,
      animalCount: 2,
      maxAnimals: 4,
      isFed: false,
      fedAt: null,
      duration: 45,
      readyToCollect: 0,
    },
    pig: {
      id: 'pig',
      unlocked: false,
      animalCount: 1,
      maxAnimals: 3,
      isFed: false,
      fedAt: null,
      duration: 65,
      readyToCollect: 0,
    },
  },
  factories: {
    windmill: {
      id: 'windmill',
      unlocked: true,
      activeRecipeId: null,
      startedAt: null,
      duration: 0,
      readyItemsCount: 0,
    },
    bakery: {
      id: 'bakery',
      unlocked: false,
      activeRecipeId: null,
      startedAt: null,
      duration: 0,
      readyItemsCount: 0,
    },
    dairy: {
      id: 'dairy',
      unlocked: false,
      activeRecipeId: null,
      startedAt: null,
      duration: 0,
      readyItemsCount: 0,
    },
    juicePress: {
      id: 'juicePress',
      unlocked: false,
      activeRecipeId: null,
      startedAt: null,
      duration: 0,
      readyItemsCount: 0,
    },
  },
  orders: INITIAL_ORDERS,
  deliveryTruck: {
    status: 'idle',
    departureTime: null,
    duration: 15, // 15 seconds to deliver and return
    currentOrderId: null,
    pendingReward: null,
  },
  weather: 'sunny',
  weatherChangedAt: Date.now(),
  quests: INITIAL_QUESTS,
  achievements: INITIAL_ACHIEVEMENTS,
  soundEnabled: true,
  gameSpeed: 1,
  stats: {
    cropsHarvested: 0,
    animalGoodsCollected: 0,
    factoryGoodsProduced: 0,
    truckDeliveriesCompleted: 0,
    totalCoinsEarned: 150,
  },
};
