import {
  CropDefinition,
  AnimalDefinition,
  VehicleDefinition,
  MarketRoute,
  RecipeDefinition,
  Season,
  WeatherType,
} from '../types/farmSystem';

export const CROPS_CONFIG: Record<string, CropDefinition> = {
  rau_cai: {
    id: 'rau_cai',
    name: 'Rau cải',
    icon: '🥬',
    seedPrice: 6,
    growDays: 2,
    yield: 6,
    basePrice: 5,
    seasons: ['spring', 'autumn', 'winter'],
    unlockLevel: 1, // Will remove level system later, keeping field to avoid type error
    shelfLifeDays: 2,
    waterNeed: 15,
    description: 'Rau cải xanh tươi, sinh trưởng nhanh, cần thu hoạch và bán sớm vì dễ héo.',
  },
  khoai_lang: {
    id: 'khoai_lang',
    name: 'Khoai lang',
    icon: '🍠',
    seedPrice: 8,
    growDays: 4,
    yield: 8,
    basePrice: 5,
    seasons: ['autumn', 'winter'],
    unlockLevel: 1,
    shelfLifeDays: 15,
    waterNeed: 10,
    description: 'Khoai lang dễ trồng, hợp đất cát, để được lâu trong kho.',
  },
  tomato: {
    id: 'tomato',
    name: 'Cà chua',
    icon: '🍅',
    seedPrice: 15,
    growDays: 4,
    yield: 6,
    basePrice: 9,
    seasons: ['spring', 'autumn'],
    unlockLevel: 1,
    shelfLifeDays: 4,
    waterNeed: 25,
    description: 'Ưa nắng, cho quả mọng đỏ thơm, dùng làm tương cà hảo hạng.',
  },
  corn: {
    id: 'corn',
    name: 'Ngô (Bắp)',
    icon: '🌽',
    seedPrice: 14,
    growDays: 5,
    yield: 8,
    basePrice: 7,
    seasons: ['summer', 'autumn'],
    unlockLevel: 1,
    shelfLifeDays: 20,
    waterNeed: 30,
    description: 'Bắp vàng chắc hạt, thức ăn bổ dưỡng cho bò sữa và heo.',
  },
  lua_nuoc: {
    id: 'lua_nuoc',
    name: 'Lúa nước',
    icon: '🌾',
    seedPrice: 12,
    growDays: 7,
    yield: 14,
    basePrice: 6,
    seasons: ['spring', 'summer'],
    unlockLevel: 1,
    shelfLifeDays: 60,
    waterNeed: 40,
    description: 'Cây lương thực cốt lõi, trồng lâu nhưng bù lại bảo quản được rất lâu.',
  },
  strawberry: {
    id: 'strawberry',
    name: 'Dâu tây',
    icon: '🍓',
    seedPrice: 30,
    growDays: 6,
    yield: 9,
    basePrice: 11,
    seasons: ['winter', 'spring'],
    unlockLevel: 1,
    shelfLifeDays: 2,
    waterNeed: 25,
    description: 'Quả ngọt mọng nước, giá trị cao nhưng khó bảo quản tươi.',
  },
};

export const ANIMALS_CONFIG: Record<string, AnimalDefinition> = {
  chicken: {
    id: 'chicken',
    name: 'Gà đẻ trứng',
    icon: '🐔',
    buyPrice: 60,
    feedPerDay: 1,
    feedItemId: 'lua_nuoc', // Changed from wheat to lua_nuoc for now
    requiresWater: false,
    produceItemId: 'egg',
    produceDays: 1,
    produceAmount: 1,
    baseSellPrice: 9, // Egg price
    unlockLevel: 1,
  },
  duck: {
    id: 'duck',
    name: 'Vịt đẻ',
    icon: '🦆',
    buyPrice: 70,
    feedPerDay: 1,
    feedItemId: 'lua_nuoc',
    requiresWater: true,
    produceItemId: 'duck_egg',
    produceDays: 1,
    produceAmount: 1,
    baseSellPrice: 10,
    unlockLevel: 1,
  },
  cow: {
    id: 'cow',
    name: 'Bò sữa',
    icon: '🐮',
    buyPrice: 500,
    feedPerDay: 2,
    feedItemId: 'corn',
    requiresWater: true,
    produceItemId: 'milk',
    produceDays: 1,
    produceAmount: 2,
    baseSellPrice: 14,
    unlockLevel: 1,
  },
  pig: {
    id: 'pig',
    name: 'Heo thịt',
    icon: '🐷',
    buyPrice: 120,
    feedPerDay: 2,
    feedItemId: 'khoai_lang',
    requiresWater: true,
    produceItemId: 'pork', // Needs to be slaughtered to get pork
    produceDays: 14,
    produceAmount: 1,
    baseSellPrice: 260,
    unlockLevel: 1,
  },
};

export const VEHICLES_CONFIG: Record<string, VehicleDefinition> = {
  handcart: {
    id: 'handcart',
    name: 'Xe đẩy tay',
    icon: '🛒',
    capacity: 20,
    tripDays: 0,
    cost: 0,
    routes: ['village'],
    isColdStorage: false,
    unlockLevel: 1,
    buyPrice: 0,
  },
  ox_cart: {
    id: 'ox_cart',
    name: 'Xe bò kéo',
    icon: '🐂',
    capacity: 60,
    tripDays: 1,
    cost: 10,
    routes: ['village', 'district'],
    isColdStorage: false,
    unlockLevel: 5,
    buyPrice: 250,
  },
  small_truck: {
    id: 'small_truck',
    name: 'Xe tải nhỏ',
    icon: '🛻',
    capacity: 200,
    tripDays: 1,
    cost: 40,
    routes: ['village', 'district', 'town'],
    isColdStorage: false,
    unlockLevel: 12,
    buyPrice: 800,
  },
  refrigerated_truck: {
    id: 'refrigerated_truck',
    name: 'Xe lạnh chuyên dụng',
    icon: '🚛',
    capacity: 150,
    tripDays: 1,
    cost: 80,
    routes: ['village', 'district', 'town', 'city'],
    isColdStorage: true,
    unlockLevel: 15,
    buyPrice: 1500,
  },
};

export const ROUTES_CONFIG: Record<string, MarketRoute> = {
  village: {
    id: 'village',
    name: 'Chợ Làng Cạnh Nhà',
    distance: '1 km',
    priceBonusPercent: 0, // 100% base price
    unlockLevel: 1,
    travelDays: 0,
    riskFactor: 0,
  },
  district: {
    id: 'district',
    name: 'Chợ Huyện Trung Tâm',
    distance: '15 km',
    priceBonusPercent: 25, // +25% price
    unlockLevel: 5,
    travelDays: 1,
    riskFactor: 0.05,
  },
  town: {
    id: 'town',
    name: 'Thị Trấn Nắng Vàng',
    distance: '45 km',
    priceBonusPercent: 50, // +50% price
    unlockLevel: 12,
    travelDays: 1,
    riskFactor: 0.1,
  },
  city: {
    id: 'city',
    name: 'Đại Đô Thị Cảng',
    distance: '120 km',
    priceBonusPercent: 90, // +90% price
    unlockLevel: 15,
    travelDays: 1.5,
    riskFactor: 0.15,
  },
};

export const RECIPES_CONFIG: RecipeDefinition[] = [
  {
    id: 'flour',
    name: 'Bột mì mịn',
    icon: '🌾',
    factoryType: 'windmill',
    ingredients: [{ itemId: 'wheat', name: 'Lúa mì', amount: 2 }],
    outputItemId: 'flour',
    outputAmount: 1,
    craftDays: 1,
    unlockLevel: 5,
    basePrice: 16,
  },
  {
    id: 'corn_flour',
    name: 'Bột ngô vàng',
    icon: '🌽',
    factoryType: 'windmill',
    ingredients: [{ itemId: 'corn', name: 'Ngô', amount: 2 }],
    outputItemId: 'corn_flour',
    outputAmount: 1,
    craftDays: 1,
    unlockLevel: 6,
    basePrice: 24,
  },
  {
    id: 'bread',
    name: 'Bánh mì nóng giòn',
    icon: '🍞',
    factoryType: 'bakery',
    ingredients: [
      { itemId: 'flour', name: 'Bột mì', amount: 1 },
      { itemId: 'egg', name: 'Trứng gà', amount: 1 },
    ],
    outputItemId: 'bread',
    outputAmount: 1,
    craftDays: 1,
    unlockLevel: 5,
    basePrice: 35,
  },
  {
    id: 'strawberry_cake',
    name: 'Bánh kem dâu tây',
    icon: '🍰',
    factoryType: 'bakery',
    ingredients: [
      { itemId: 'flour', name: 'Bột mì', amount: 1 },
      { itemId: 'strawberry', name: 'Dâu tây', amount: 2 },
      { itemId: 'egg', name: 'Trứng gà', amount: 1 },
    ],
    outputItemId: 'strawberry_cake',
    outputAmount: 1,
    craftDays: 1.5,
    unlockLevel: 8,
    basePrice: 68,
  },
  {
    id: 'butter',
    name: 'Bơ tươi thượng hạng',
    icon: '🧈',
    factoryType: 'dairy',
    ingredients: [{ itemId: 'milk', name: 'Sữa tươi', amount: 1 }],
    outputItemId: 'butter',
    outputAmount: 1,
    craftDays: 1,
    unlockLevel: 8,
    basePrice: 28,
  },
  {
    id: 'cheese',
    name: 'Phô mai vàng béo',
    icon: '🧀',
    factoryType: 'dairy',
    ingredients: [{ itemId: 'milk', name: 'Sữa tươi', amount: 2 }],
    outputItemId: 'cheese',
    outputAmount: 1,
    craftDays: 2,
    unlockLevel: 9,
    basePrice: 60,
  },
  {
    id: 'strawberry_jam',
    name: 'Mứt dâu tây ngọt',
    icon: '🍓',
    factoryType: 'jam_press',
    ingredients: [{ itemId: 'strawberry', name: 'Dâu tây', amount: 2 }],
    outputItemId: 'strawberry_jam',
    outputAmount: 1,
    craftDays: 1,
    unlockLevel: 8,
    basePrice: 45,
  },
  {
    id: 'tomato_sauce',
    name: 'Sốt cà chua nguyên chất',
    icon: '🥫',
    factoryType: 'jam_press',
    ingredients: [{ itemId: 'tomato', name: 'Cà chua', amount: 2 }],
    outputItemId: 'tomato_sauce',
    outputAmount: 1,
    craftDays: 1,
    unlockLevel: 6,
    basePrice: 30,
  },
];

export const ALL_ITEMS_CATALOG: Record<
  string,
  { name: string; icon: string; category: string; basePrice: number; isPerishable: boolean; shelfLifeDays: number }
> = {
  wheat: { name: 'Lúa mì', icon: '🌾', category: 'crop', basePrice: 6, isPerishable: false, shelfLifeDays: 20 },
  carrot: { name: 'Cà rốt', icon: '🥕', category: 'crop', basePrice: 7, isPerishable: true, shelfLifeDays: 10 },
  tomato: { name: 'Cà chua', icon: '🍅', category: 'crop', basePrice: 8, isPerishable: true, shelfLifeDays: 6 },
  corn: { name: 'Ngô', icon: '🌽', category: 'crop', basePrice: 9, isPerishable: false, shelfLifeDays: 14 },
  pumpkin: { name: 'Bí ngô', icon: '🎃', category: 'crop', basePrice: 18, isPerishable: false, shelfLifeDays: 30 },
  strawberry: { name: 'Dâu tây', icon: '🍓', category: 'crop', basePrice: 14, isPerishable: true, shelfLifeDays: 5 },
  egg: { name: 'Trứng gà', icon: '🥚', category: 'animal_product', basePrice: 8, isPerishable: true, shelfLifeDays: 7 },
  milk: { name: 'Sữa bò tươi', icon: '🥛', category: 'animal_product', basePrice: 14, isPerishable: true, shelfLifeDays: 4 },
  wool: { name: 'Lông cừu', icon: '🧶', category: 'animal_product', basePrice: 30, isPerishable: false, shelfLifeDays: 60 },
  honey: { name: 'Mật ong rừng', icon: '🍯', category: 'animal_product', basePrice: 22, isPerishable: false, shelfLifeDays: 60 },
  flour: { name: 'Bột mì', icon: '🌾', category: 'processed', basePrice: 16, isPerishable: false, shelfLifeDays: 25 },
  corn_flour: { name: 'Bột ngô', icon: '🌽', category: 'processed', basePrice: 24, isPerishable: false, shelfLifeDays: 25 },
  bread: { name: 'Bánh mì', icon: '🍞', category: 'processed', basePrice: 35, isPerishable: true, shelfLifeDays: 5 },
  strawberry_cake: { name: 'Bánh kem dâu', icon: '🍰', category: 'processed', basePrice: 68, isPerishable: true, shelfLifeDays: 4 },
  butter: { name: 'Bơ tươi', icon: '🧈', category: 'processed', basePrice: 28, isPerishable: true, shelfLifeDays: 8 },
  cheese: { name: 'Phô mai', icon: '🧀', category: 'processed', basePrice: 60, isPerishable: true, shelfLifeDays: 14 },
  strawberry_jam: { name: 'Mứt dâu', icon: '🍓', category: 'processed', basePrice: 45, isPerishable: false, shelfLifeDays: 30 },
  tomato_sauce: { name: 'Sốt cà chua', icon: '🥫', category: 'processed', basePrice: 30, isPerishable: false, shelfLifeDays: 30 },
  fertilizer: { name: 'Phân bón hữu cơ', icon: '🧪', category: 'supply', basePrice: 8, isPerishable: false, shelfLifeDays: 999 },
  pesticide: { name: 'Thuốc trừ sâu sinh học', icon: '🧴', category: 'supply', basePrice: 12, isPerishable: false, shelfLifeDays: 999 },
  vet_medicine: { name: 'Thuốc thú y', icon: '💊', category: 'supply', basePrice: 25, isPerishable: false, shelfLifeDays: 999 },
};

export const LEVEL_UNLOCKS: Record<number, string[]> = {
  1: ['Đồng ruộng cơ bản (4 ô)', 'Cửa hàng hạt giống', 'Chợ làng', 'Xe đẩy tay'],
  2: ['Cây Cà rốt'],
  3: ['Chuồng gà', 'Cây Cà chua', 'Kho nâng cấp lần 1'],
  5: ['Cối xay gió & Lò bánh', 'Cây Ngô', 'Xe bò kéo', 'Chợ huyện'],
  6: ['Cây Bí ngô', 'Máy ép mứt'],
  8: ['Chuồng bò sữa', 'Cây Dâu tây', 'Xưởng chế biến sữa', 'Hệ thống tưới tự động'],
  10: ['Chuồng cừu'],
  12: ['Xe tải nhỏ', 'Thị trấn Nắng Vàng', 'Đàn ong mật', 'Nhân công tự động'],
  15: ['Xe lạnh chuyên dụng', 'Chợ Đại Đô Thị', 'Kho lạnh hiện đại'],
};

export function getXPForNextLevel(level: number): number {
  return 80 + level * 70 + Math.floor(level * level * 25);
}

export const SEASON_NAMES: Record<Season, { name: string; icon: string; desc: string }> = {
  spring: { name: 'Mùa Xuân', icon: '🌸', desc: 'Khí trời ấm áp, cây cối đâm chồi nảy lộc. Thích hợp cho Dâu tây & Lúa mì.' },
  summer: { name: 'Mùa Hạ', icon: '☀️', desc: 'Ánh nắng gay gắt, bốc hơi nước nhanh. Cà chua & Ngô phát triển cực tốt.' },
  autumn: { name: 'Mùa Thu', icon: '🍁', desc: 'Gió thu se mát, mùa vàng bội thu Bí ngô & Cà rốt.' },
  winter: { name: 'Mùa Đông', icon: '❄️', desc: 'Trời rét lạnh, đất đóng băng nhẹ. Cần tưới ấm và che chắn cây trồng.' },
};

export const WEATHER_NAMES: Record<WeatherType, { name: string; icon: string; desc: string }> = {
  sunny: { name: 'Trời Nắng Ráo', icon: '☀️', desc: 'Quang hợp tối ưu, tiêu hao độ ẩm đất bình thường.' },
  rainy: { name: 'Mưa Rào Mát Lành', icon: '🌧️', desc: 'Mưa tự động tưới nước 100% cho mọi ô đất!' },
  drought: { name: 'Hạn Hán Nắng Nóng', icon: '🔥', desc: 'Đất bốc hơi cực nhanh, cần tưới thường xuyên gấp 2 lần!' },
  storm: { name: 'Bão Gió Giật', icon: '🌪️', desc: 'Gió mạnh có nguy cơ làm hỏng mùa màng chưa thu hoạch.' },
};
